---
# Set to yes, if you're using pycharm for development
# Otherwise, set no
use_pycharm: yes
# Your linux/mac user that will run ansible
remote_user: staff
# Your linux/mac group that will run ansible
remote_group: staff
# Your project location (this repo)
project_path: "/Users/staff/Documents/WorkingDir/Projects/kartoza/kbims-healthyrivers"
# True if it will be running on Travis

on_travis: False
btsync_db:
  environment:
      # The environment file should define two variables:
      # SECRET: a RW btsync key if the server is a production server
      #         a RO btsync key if it is staging or development machine
      # DEVICE: a unique device name so you can recognise which host is being peered with in btsync
      # See the btsync example env in this folder for a template
      SECRET:
      DEVICE:

btsync_media:
  environment:
      # The environment file should define two variables:
      # SECRET: a RW btsync key if the server is a production server
      #         a RO btsync key if it is staging or development machine
      # DEVICE: a unique device name so you can recognise which host is being peered with in btsync
      # See the btsync example env in this folder for a template
      SECRET:
      DEVICE:

django:
  # Use this for debug mode. Comment for prod mode
  command: /usr/sbin/sshd -D
  environment:
    SITE_DOMAIN_NAME: 'http://kbims-healthyrivers.test'
    GEOCONTEXT_URL: 'http://localhost:65402'
    CONTACT_US_EMAIL: 'dimas@kartoza.com'
    DEBUG: True
    DJANGO_SETTINGS_MODULE: healthyrivers_core.settings.dev_docker
    RABBITMQ_HOST: rabbitmq
    HAYSTACK_HOST: elasticsearch
    PYTHONPATH: /usr/src/app:/usr/src/bims:/home/web/django_project
    ROOT_URLCONF: healthyrivers_core.urls
    DATABASE_NAME: gis
    DATABASE_PASSWORD: docker
    DATABASE_USERNAME: docker
    DATABASE_HOST: db
    SITEURL: http://kbims-healthyrivers.test/

web:
  # Use this for debug mode. Comment for prod mode
  command: debug
  # just another key to make sure web is a dict
  environment:

geonode:
  environment:
    GEONODE_INSTANCE_NAME: geonode
    DEFAULT_BACKEND_DATASTORE: datastore
    GEONODE_DATABASE: gis
    GEONODE_DATABASE_USER: docker
    GEONODE_DATABASE_PASSWORD: docker
    GEONODE_GEODATABASE: geonode_data
    GEONODE_GEODATABASE_PASSWORD: geonode_data
    UWSGI_CMD: uwsgi --ini /usr/src/app/uwsgi.ini
    IS_CELERY: False
    C_FORCE_ROOT: 1
    # replaced with defaults in settings
    GEOSERVER_PUBLIC_LOCATION: kbims-healthyrivers.test/geoserver/
    GEOSERVER_LOCATION: http://geoserver:8080/geoserver/
    STATIC_ROOT: /home/web/static
    MEDIA_ROOT: /home/web/media
    GEOIP_PATH: /home/web/media/geoip.db
    ALLOWED_HOSTS: ['kbims-healthyrivers.test']
    ADMIN_EMAILS: dimas@kartoza.com
    GEOSERVER_ADMIN_PASSWORD: admingeoserver

geoserver:
  environment:
    GEOSERVER_ADMIN_PASSWORD: admingeoserver
    SITEURL: http://kbims-healthyrivers.test/

interpreters:
  django:
    name: 'Healthyrivers Container'
    domain_alias: 'kbims-healthyrivers.test'
    ssh_port: &inasafe_django_ssh_port 62303
    pycharm_helpers: /home/web/django_project/.pycharm_helpers
    ipaddress: &inasafe_django_host_ip kbims-healthyrivers.test

docker_port_forward:
  django:
    db: 6543
    elastic_search: 9200
    ssh: 62303
    karma_tests: 62304
  web:
    http: 62302
